### ISSUE TITLE
Add list of defined categories

### ISSUE THREAD

**Issue by sagIoTPower** [SoftwareAG/apama-analytics-builder-block-sdk#4]
Could you pls. add a list of the defined categories in the documentation, e.g.
* @$blockCategory Input
* @$blockCategory Output
* @$blockCategory Logic
* @$blockCategory Calculations
* @$blockCategory Aggregates
* @$blockCategory Flow Manipulation
* @$blockCategory Utilities

Currently only these categories can be used.

**Comment by ben-spiller** [comment]
Thanks we have added this to our internal backlog (PAB-3148)

**Comment by skom-sag** [comment]
This is resolved with 10.14.0.3 release (see https://github.com/SoftwareAG/apama-analytics-builder-block-sdk/blob/rel/10.14.0.x/doc/020-NamingAndDoc.md#allowed-categories for more info)
