### ISSUE TITLE
SDK does not work Apama Core Components installation

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/apama-analytics-builder-block-sdk#6]
the Apama Core installation:
https://techcommunity.softwareag.com/en_en/apama-downloads.html

does not include a JRE and the SDK cannot use a Java installation outside of the Apama. The SDK should use the OS JAVA_HOME as a fallback.

**Comment by skom-sag** [comment]
Raised an internal issue to track this

**Comment by skom-sag** [comment]
Turns out the SDK requires a full apama installation. Improved the documentation accordingly.
